# 数据操作

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#入门" data-toc-modified-id="入门-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>入门</a></span></li><li><span><a href="#运算符" data-toc-modified-id="运算符-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>运算符</a></span></li><li><span><a href="#广播机制" data-toc-modified-id="广播机制-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>广播机制</a></span></li><li><span><a href="#切片和索引" data-toc-modified-id="切片和索引-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>切片和索引</a></span></li><li><span><a href="#节省内存" data-toc-modified-id="节省内存-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>节省内存</a></span></li><li><span><a href="#转化为其他Python对象" data-toc-modified-id="转化为其他Python对象-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>转化为其他Python对象</a></span></li></ul></div>

## 入门

In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape, x.size(), x.numel()

(torch.Size([12]), torch.Size([12]), 12)

In [4]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [5]:
X.shape, X.size(), X.numel()

(torch.Size([3, 4]), torch.Size([3, 4]), 12)

In [6]:
x.reshape(-1, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.randn(3, 4)

tensor([[ 0.7731, -0.6806,  0.0771,  0.3620],
        [-0.1601,  0.3129, -0.5586,  1.0968],
        [-0.0181,  0.4778, -0.3982, -2.0504]])

列表转张量

In [9]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 运算符 

In [10]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [11]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

张量拼接

In [12]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

逻辑运算

In [13]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

聚合

In [14]:
X.sum()

tensor(66.)

## 广播机制

1. 通过适当复制元素来扩展⼀个或两个数组，以便在转换之后，两个张量具有相同的形状；

2. 对⽣成的数组执⾏按元素操作。


In [15]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [16]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 切片和索引

In [17]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [18]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [19]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 节省内存

In [20]:
before = id(Y)
Y = Y + X
id(Y) == before

False

这可能是不可取的，原因有两个：

1. ⾸先，我们不想总是不必要地分配内存。在机器学习中，我们可能有数百兆的参数，并且在⼀秒内多次 更新所有参数。通常情况下，我们希望原地执⾏这些更新；

2. 如果我们不原地更新，其他引⽤仍然会指向旧的内存位置，这样我们的某些代码可能会⽆意中引⽤旧 的参数。

In [21]:
Z = torch.zeros_like(Y)
print("id(Z): ", id(Z))
Z[:] = X + Y
print("id(Z): ", id(Z))

id(Z):  140384437795952
id(Z):  140384437795952


使用`+=`来原地修改数据，减少内存开销

In [22]:
before = id(X)
X += Y
before == id(X)

True

## 转化为其他Python对象

np.ndarray 和 tensor 转化

In [23]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

要将⼤⼩为1的张量转换为Python标量，我们可以调⽤item函数或Python的内置函数。

In [24]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)