# 线性代数

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#标量" data-toc-modified-id="标量-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>标量</a></span></li><li><span><a href="#向量" data-toc-modified-id="向量-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>向量</a></span><ul class="toc-item"><li><span><a href="#长度、纬度和形状" data-toc-modified-id="长度、纬度和形状-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>长度、纬度和形状</a></span></li></ul></li><li><span><a href="#矩阵" data-toc-modified-id="矩阵-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>矩阵</a></span></li><li><span><a href="#张量" data-toc-modified-id="张量-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>张量</a></span></li><li><span><a href="#张量算法的基本性质" data-toc-modified-id="张量算法的基本性质-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>张量算法的基本性质</a></span></li><li><span><a href="#降维" data-toc-modified-id="降维-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>降维</a></span><ul class="toc-item"><li><span><a href="#非降维求和" data-toc-modified-id="非降维求和-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>非降维求和</a></span></li></ul></li><li><span><a href="#点积(Dot-Product)" data-toc-modified-id="点积(Dot-Product)-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>点积(Dot Product)</a></span></li><li><span><a href="#矩阵-向量积" data-toc-modified-id="矩阵-向量积-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>矩阵-向量积</a></span></li><li><span><a href="#矩阵-矩阵乘法" data-toc-modified-id="矩阵-矩阵乘法-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>矩阵-矩阵乘法</a></span></li><li><span><a href="#范数" data-toc-modified-id="范数-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>范数</a></span><ul class="toc-item"><li><span><a href="#范数和目标" data-toc-modified-id="范数和目标-10.1"><span class="toc-item-num">10.1&nbsp;&nbsp;</span>范数和目标</a></span></li></ul></li><li><span><a href="#关于线性代数的更多信息" data-toc-modified-id="关于线性代数的更多信息-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>关于线性代数的更多信息</a></span></li></ul></div>

## 标量
采用数学表示法，其中标量变量用小写字母表示（例如： $x、y或z$ ），用$\mathbb{R}$表示所有连续实数标量的空间，表达式$x\in\mathbb{R}$是表示$x$是一个实值标量的正式形式。

符号$\in$称为“属于”，表示“是集合中的成员”。例如$x,y\in\{0,1\}$用来表示$x和y$只能为0或1的数字。

标量由只有一个元素的张量表示。下面代码将实例化两个标量，并执行一些算术运算：

In [1]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 向量
向量可以视作标量组成的列表。这些标量称为向量的元素(element)或分量(component)。当向量表示数据集中的样本时，它们的值具有一定的现实意义。

例如，如果我们正在训练⼀个模型来预测贷款违约⻛险，可能会将每个申请⼈与⼀个向量相关联，其分量与其收⼊、⼯作年限、过往违约次数和其他因素相对应。

如果我们正在研究医院患者可能⾯临的⼼脏病发作⻛险，可能会⽤⼀个向量来表⽰每个患者，其分量 为最近的⽣命体征、胆固醇⽔平、每天运动时间等。

在数学表⽰法中，向量通常记为粗体、⼩写的符号（例如$\textbf{x、y}和\textbf{z}$）

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

我们可以使⽤下标来引⽤向量的任⼀元素，例如可以通过x i 来引⽤第i个元素。注意，元素x i 是⼀个标量，所以 我们在引⽤它时不会加粗。⼤量⽂献认为列向量是向量的默认⽅向，在本书中也是如此。在数学中，向量x可 以写为：

$$\textbf{x} = \left[\begin{matrix}
x_1\\
x_2\\
\vdots\\
x_n
\end{matrix}\right]$$
其中$x_1,\dots,x_n$是向量元素，代码中可以用索引来访问：

In [3]:
x[3]

tensor(3)

### 长度、纬度和形状
向量只是⼀个数字数组，就像每个数组都有⼀个⻓度⼀样，每个向量也是如此。

在数学表⽰法中，如果我们想说⼀个向量$\textbf{x}$由n个实值标量组成，可以将其表⽰为$x\in\mathbb{R}^n$。

向量的⻓度通常称为向量的维度（dimension），与普通的`Python数组`⼀样，我们可以通过调⽤Python的内置`len()`函数来访问张量的⻓度。

In [4]:
len(x)

4

当用张量表示一个向量（只有一个轴）时，我们也可以通过`.shape`来属性访问向量的长度。形状（shape）是⼀个元素组，列出了张量沿每个轴的⻓度（维数）。对于只有⼀个轴的张量，形状只有⼀个元素。

In [5]:
x.shape

torch.Size([4])

**请注意**，*维度（dimension）* 这个词在不同上下⽂时往往会有不同的含义，这经常会使⼈感到困惑。

为了清楚起⻅，我们在此明确⼀下：向量或轴的维度被⽤来表⽰向量或轴的`⻓度`，即向量或轴的元素数量。然⽽，张量的维度⽤来表⽰张量具有的`轴数`。在这个意义上，张量的某个轴的维数就是这个轴的⻓度。

## 矩阵
正如向量将标量从零阶推⼴到⼀阶，矩阵将向量从⼀阶推⼴到⼆阶。

矩阵，我们通常⽤粗体、⼤写字⺟来表示（例如：$\textbf{X、Y}$和$\textbf{Z}$），代码中表示有两个轴的张量。

数学表示法使用$\textbf{A}\in\mathbb{R}^{m \times n}$来表示矩阵$\textbf{A}$，其由$m$行和$n$列的标量组成。我们可以将任意矩阵$\textbf{A}\in\mathbb{R}^{m \times n}$视为一个表格，其中每个元素$a_ij$属于第$i$行第$j$列：

$$\textbf{A} = \left [ \begin{matrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{matrix} \right ]$$

对于任意矩阵$\textbf{A}\in\mathbb{R}^{m \times n}$，$\textbf{A}$的形状是$(m, n)$或$m \times n$。当矩阵具有相同数量的⾏和列时，其形状将变为正⽅形；因此，它被称为⽅阵（square matrix）。

In [6]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

我们可以通过行索引$(i)$和列索引$(j)$来访问矩阵中的标量元素$a_{ij}$，例如$[\textbf{A}]_{ij}$。

为了表⽰起来简单，只有在必要时才会将逗号插⼊到单独的索引中，例如$a_{2,3j}$和$[\textbf{A}]_{2i-1,3}$。

当我们交换矩阵的⾏和列时，结果称为矩阵的转置（transpose）。通常用$\textbf{a}^\top$表示,如果$\textbf{B}=\textbf{A}^\top$，则对于任意的$i和j$,都有$b_{ij}=a_{ji}$。因此表示上文中的$\textbf{A}$的转置矩阵$(n\times m)$：

$$\textbf{A}^\top = \left [\begin{matrix}
a_{11} & a_{21} & \cdots & a_{m1} \\
a_{12} & a_{22} & \cdots & a_{m2} \\
\vdots & \vdots & \ddots & \vdots \\
a_{1n} & a_{2n} & \cdots & a_{mn}
\end{matrix} \right]$$

代码中实现：

In [7]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

作为⽅阵的⼀种特殊类型，对称矩阵（symmetric matrix）$\textbf{A}$等于其转置：$\textbf{A}=\textbf{A}^\top$。定义一个对称矩阵$\textbf{B}$:

In [8]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [9]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

矩阵是有⽤的数据结构：它们允许我们组织具有不同模式的数据。例如，我们矩阵中的⾏可能对应于不同的房屋（数据样本），⽽列可能对应于不同的属性。

因此，尽管单个向量的默认⽅向是列向量，但在表示表格数据集的矩阵中，将每个数据样本作为矩阵中的⾏向量更为常⻅。后⾯的章节将讲到这点，这种约定将⽀持常⻅的深度学习实践。例如，沿着张量的最外轴，我们可以访问或遍历⼩批量的数据样本。

## 张量
就像向量是标量的推⼴，矩阵是向量的推⼴⼀样，我们可以构建具有更多轴的数据结构。张量是描述具有任意轴数的$n$维数组的通用方法。

张量⽤特殊字体的⼤写字⺟表⽰（例如，$X、Y和Z$），它们的索引机制（例如$x_{ijk}和[X]_{1,2i-1,3}$）与矩阵类似。

In [10]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 张量算法的基本性质
标量、向量、矩阵和任意数量轴的张量有一些实用的属性。例如任何按元素的⼀元运算都不会改变其操作数的形状。

同样，给定具有相同形状的任意两个张量，任何按元素⼆元运算的结果都将是相同形状的张量。例如，将两个相同形状的矩阵相加，会在这两个矩阵上执⾏元素加法。

In [11]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() #分配新的内存，A的副本给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

具体⽽⾔，两个矩阵的按元素乘法称为Hadamard积（Hadamard product）（数学符号$\odot$）对于矩阵$\textbf{B}\in\mathbb{R}^{m\times n}$，其中$i$行$j$列的元素是$b_{ij}$，$\textbf{A}和\textbf{B}$的hadamard积为：

$$\textbf{A}⊙\textbf{B}=\left[\begin{matrix}
a_{11}b_{11} & a_{12}b_{12} & \cdots & a_{1n}b_{1n} \\
a_{21}b_{21} & a_{22}b_{22} & \cdots & a_{2n}b_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1}b_{m1} & a_{m2}b_{m2} & \cdots & a_{mn}b_{mn} \\
\end{matrix}\right]$$

In [12]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

- 广播原则

将张量乘以或加上⼀个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。

In [13]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 降维
我们可以对任意张量进⾏的⼀个有⽤的操作是计算其元素的和。数学表示法使用$\sum$符号表示求和。

表示长度为d的向量中元素的和，可以记做$\sum_{i=1}^{d}x_{i}$，代码实现使用求和函数：

In [14]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

我们可以对任意形状张量求和，例如矩阵$\textbf{A}$中元素和可以记为$\sum_{i=1}^{m}\sum_{j=1}^{n}a_{ij}$。

In [15]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

默认情况下，调⽤求和函数会沿所有的轴降低张量的维度，使它变为⼀个标量。我们还可以指定张量沿哪⼀个轴来通过求和降低维度。

以矩阵为例，为了通过求和所有⾏的元素来降维（轴0），可以在调⽤函数时指 定axis=0。由于输⼊矩阵沿0轴降维以⽣成输出向量，因此输⼊轴0的维数在输出形状中消失。

In [16]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [17]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

沿着矩阵行和列求和，等价于对矩阵所有元素求和：

In [18]:
A.sum(axis=[0, 1])

tensor(190.)

一个与求和相关的量是平均值（mean,average）。通过元素和除以元素总数来计算平均值，代码中我们可以计算任意形状张量的平均值：

In [19]:
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

同样，计算平均值的函数也可以沿指定轴降低张量的维度。

In [20]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

### 非降维求和
但是，有时在调⽤函数来计算总和或均值时保持轴数不变会很有⽤。

In [21]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

sum_A求和保持了两个轴，可以通过广播原则A除sum_A

In [22]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

如果我们想沿某个轴计算A元素的累积总和，⽐如axis=0（按⾏计算），可以调⽤cumsum函数。此函数不会沿任何轴降低输⼊张量的维度。

In [23]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

## 点积(Dot Product)

学习了按元素操作，求和几平均值。另一个基本操作就是点积。给定两个向量$\textbf{x,y} \in \mathbb{R}^{d}$，它们的点积$\textbf{x}^\top\textbf{y}=$或（$\left\langle\textbf{x,y}\right\rangle$）,是相同位置元素乘积的和：$\textbf{x}^\top\textbf{y}=\sum_{i=1}^{d}{x_{i}y_{i}}$。

In [24]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

同样可以进行按位相乘然后求和实现：

In [25]:
torch.sum(x*y)

tensor(6.)

点积在很多场合都很有用，例如，给定⼀组由向量$\textbf{x}\in\mathbb{R}^{d}$表示的值，和一组由$\textbf{w}\in\mathbb{R}^{d}$表示的权重。$\textbf{x}$中的值根据权重$\textbf{w}$的加权和，可以表⽰为点积$\textbf{x}^\top\textbf{w}$。当权重为⾮负数且和为1(即$\big(\sum_{i=1}^{d}\textbf{w}_{i}=1\big)$)时，点积表示加权平均。

将两个向量规范化后得到单位长度后，点积表⽰它们夹⻆的余弦即($\mathbf{a\cdot b}=\lvert a\rvert\lvert b\rvert\cos\theta$)。

## 矩阵-向量积

定义矩阵$\textbf{A}\in\mathbb{R}^{m\times n}$和向量$\textbf{x}\in\mathbb{R}^{n}$，矩阵$\textbf{A}$用行向量表示：

$$\textbf{A}=\left[\begin{matrix}
\textbf{a}^\top_1 \\
\textbf{a}^\top_2 \\
\vdots \\
\textbf{a}^\top_m \\
\end{matrix}\right]$$

其中每个$\textbf{a}^\top_i\in\mathbb{R}^n$都是行向量，表示矩阵的第$i$行。矩阵向量积$\textbf{Ax}$是长度为$m$的列向量，其中第$i$个元素是点积$\textbf{a}_i^\top\textbf{x}$:

$$\textbf{Ax}=\left[\begin{matrix}
\textbf{a}^\top_1\textbf{x} \\
\textbf{a}^\top_2\textbf{x} \\
\vdots \\
\textbf{a}^\top_m\textbf{x} \\
\end{matrix}\right]$$

我们可以把一个矩阵$\textbf{A}\in\mathbb{R}^{m\times n}$乘法看作是从$\mathbb{R}^{m\times n}$到$\mathbb{R}^{m}$向量的转换。这些转换是⾮常有⽤的，例如可以⽤⽅阵的乘法来表⽰旋转。

我们也可以使⽤矩阵-向量积来描述在给定前⼀层的值时，求解神经⽹络每⼀层所需的复杂计算。

在代码中使⽤张量表⽰矩阵-向量积，我们使⽤`mv`函数。当我们为矩阵$\textbf{A}$和向量$\textbf{x}$调⽤`torch.mv(A, x)`时，会执⾏矩阵-向量积。**注意，A的列维数（沿轴1的⻓度）必须与x的维数（其⻓度）相同。**

In [26]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

## 矩阵-矩阵乘法

向量积的基础上推广到矩阵乘法比较简单了，假设两个矩阵$\textbf{A}\in\mathbb{R}^{n\times k}$和$\textbf{B}\in\mathbb{R}^{k\times m}$:

$$\textbf{A}=\left[\begin{matrix}
a_{11} & a_{12} & \cdots & a_{1k} \\
a_{21} & a_{22} & \cdots & a_{2k} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nk} \\
\end{matrix}\right],
\textbf{B}=\left[\begin{matrix}
b_{11} & b_{12} & \cdots & b_{1m} \\
b_{21} & b_{22} & \cdots & b_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
b_{k1} & b_{k2} & \cdots & b_{km} \\
\end{matrix}\right]
$$

用行向量$\textbf{a}_{i}^{\top}\in\mathbb{R}^{k}$表示矩阵$\textbf{A}$的第$i$行，并让列向量$\textbf{b}_{j}\in\mathbb{R}^{k}$作为矩阵$\textbf{B}$的第$j$列。生成矩阵$\textbf{C}=\textbf{AB}$最简单的方法是考虑$\textbf{A}$的行向量和$\textbf{B}$的列向量:

$$
\textbf{A}=\left[\begin{matrix}
a_{1}^{\top} \\
a_{2}^{\top} \\
\vdots \\
a_{n}^{\top} \\
\end{matrix}\right],
\textbf{B}=\left[\begin{matrix}
b_{1} & b_{2} & \cdots & b_{m}
\end{matrix}\right]
$$

当我们简单地将每个元素$\textbf{c}_{ij}$计算为点积$\textbf{a}_i^{\top}\textbf{b}_{j}$:

$$
\textbf{C}=\textbf{AB}=
\left[\begin{matrix}
a_{1}^{\top} \\
a_{2}^{\top} \\
\vdots \\
a_{n}^{\top} \\
\end{matrix}\right]
\left[\begin{matrix}
b_{1} & b_{2} & \cdots & b_{m}
\end{matrix}\right]=
\left[\begin{matrix}
\textbf{a}_{1}^{\top}\textbf{b}_{1}&\textbf{a}_{1}^{\top}\textbf{b}_{2}&\cdots&\textbf{a}_{1}^{\top}\textbf{b}_{m}\\
\textbf{a}_{2}^{\top}\textbf{b}_{1}&\textbf{a}_{2}^{\top}\textbf{b}_{2}&\cdots&\textbf{a}_{2}^{\top}\textbf{b}_{m}\\
\vdots & \vdots & \ddots & \vdots \\
\textbf{a}_{n}^{\top}\textbf{b}_{1}&\textbf{a}_{n}^{\top}\textbf{b}_{2}&\cdots&\textbf{a}_{n}^{\top}\textbf{b}_{m}\\
\end{matrix}\right]
$$

我们可以将矩阵-矩阵乘法$\textbf{AB}$看作简单地执⾏$m$次矩阵-向量积，并将结果拼接在⼀起，形成⼀个$n\times m$矩阵。

在下⾯的代码中，我们在$\textbf{A}和\textbf{B}$上执⾏矩阵乘法。这⾥的$\textbf{A}$是⼀个5⾏4列的矩阵，$\textbf{B}$是⼀个4⾏3列的矩阵。两者相乘后，我们得到了⼀个5⾏3列的矩阵。

In [27]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

矩阵-矩阵乘法可以简单地称为**矩阵乘法**，不应与”Hadamard积”混淆。

## 范数

线性代数中最有⽤的⼀些运算符是范数（norm）。⾮正式地说，向量的范数是表⽰⼀个向量有多⼤。这⾥考虑的⼤⼩（size）概念不涉及维度，⽽是**分量的⼤⼩**。

在线性代数中，向量范数是将向量映射到标量的函数$f$。给定任意向量$\textbf{x}$，向量范数要满⾜⼀些属性。

第⼀个性质是：如果我们按常数因⼦$\alpha$缩放向量的所有元素，其范数也会按相同常数因⼦的绝对值缩放：

$$f(\alpha\textbf{x})=\lvert\alpha\rvert f(\textbf{x})$$

第⼆个性质是熟悉的三⻆不等式:

$$f(\textbf{x}+\textbf{y}) \le f(\textbf{x}) + f(\textbf{y})$$

第三个性质简单地说范数必须是⾮负的:

$$f(\textbf{x})\ge 0$$

因为在⼤多数情况下，任何东西的最⼩的⼤⼩是0。最后⼀个性质要求范数最⼩为0，当且仅当向量全由0组成。

$$\forall i,[\textbf{x}]_i = 0 \Leftrightarrow f(\textbf{x}) = 0$$

范数听起来很像距离的度量。欧⼏⾥得距离和毕达哥拉斯定理中的⾮负性概念和三⻆不等式可能会给出⼀些启发。事实上，欧⼏⾥得距离是⼀个$L_2$范数：假设$n$维向量$\textbf{x}$中的元素是$x_1, x_2, \dots, x_n$，其$L_2$范数是向量元素平⽅和的平⽅根：

$$\|\textbf{x}\|_2 = \sqrt{\sum_{i=1}^{n}{x_i^2}}$$

其中，在$L_2$范数中常常省略下标2，也就是说$|\textbf{x}\|_2$等同于$|\textbf{x}\|$。

在代码中，我们可以按如下⽅式计算向量的$L_2$范数：

In [28]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

深度学习中更经常地使⽤$L_2$范数的平⽅，也会经常遇到$L_1$范数，它表⽰为向量元素的绝对值之和：
$$\|\textbf{x}\|_1 = \sum_{i=1}^{n}{\lvert x_i \rvert}$$

与$L_2$范数相⽐，$L_1$范数受异常值的影响较⼩。为了计算$L_1$范数，我们将绝对值函数和按元素求和组合起来:

In [29]:
torch.abs(u).sum()

tensor(7.)

$L_2$范数和$L_1$范数都是更⼀般的$L_p$范数的特例：
$$\|\textbf{x}\|_p = \big(\sum_{i=1}^{n}{\lvert x_i \rvert^p}\big)^{1/p}$$

类似于向量的L 2 范数，矩阵$\mathbf{X}\in \mathbb{R}^{m\times n}$的*Frobenius*范数（Frobenius norm）是矩阵元素平⽅和的平⽅根：

$$\|\mathbf{X}\|_F = \sqrt{\sum_{i=1}^m\sum_{j=1}^n{x_{ij}^2}}$$

Frobenius范数满⾜向量范数的所有性质， 它就像是矩阵形向量的$L_2$范数。 调⽤以下函数将计算矩阵的Frobenius范数:

In [30]:
torch.norm(torch.ones(4, 9))

tensor(6.)

### 范数和目标

在深度学习中，我们经常试图解决优化问题：最⼤化分配给观测数据的概率; 最⼩化预测和真实观测之间的距离。⽤向量表示物品（如单词、产品或新闻⽂章），以便最⼩化相似项⽬之间的距离，最⼤化不同项⽬之间的距离。⽬标，或许是深度学习算法最重要的组成部分（除了数据），通常被表达为范数。

## 关于线性代数的更多信息
仅⽤⼀节，我们就教会了阅读本书所需的、⽤以理解现代深度学习的线性代数。线性代数还有很多，其中很多数学对于机器学习⾮常有⽤。例如，矩阵可以分解为因⼦，这些分解可以显示真实世界数据集中的低维结构。机器学习的整个⼦领域都侧重于使⽤矩阵分解及其向⾼阶张量的泛化，来发现数据集中的结构并解决预测问题。当开始动⼿尝试并在真实数据集上应⽤了有效的机器学习模型，你会更倾向于学习更多数学。因此， 这⼀节到此结束，本书将在后⾯介绍更多数学知识。 如果渴望了解有关线性代数的更多信息，可以参考[线性代数运算的在线附录38](https://d2l.ai/chapter_appendix-mathematics-for-deep-learning/geometry-linear-algebraic-ops.html)或其他优秀资源([Kolter, 2008] Kolter, Z. (2008). Linear algebra review and reference. Available online: http.)